libraries:
  Movies:
    report_path: config/missing/Movies_missing.yml  # NOTE: this seems to do nothing at the moment
    template_variables:
      collection_mode: hide           # hide the collections in the "Library" tab
      placeholder_imdb_id: tt0117887  # put something in the placeholder so it'll be hidden - That Thing You Do! (1996)
    collection_files:  # NOTE: this was metadata_path when I first started
    - folder: config/collections/Movies
    - pmm: separator_award
    - pmm: bafta
      template_variables:
        data:
          starting: 2044  # when they started
          ending: current_year
    - pmm: golden
      template_variables:
        data:
          starting: 1944  # when they started
          ending: current_year
    - pmm: oscars
      template_variables:
        data:
          starting: 1928  # when they started
          ending: current_year
    - pmm: sundance
      template_variables:
        data:
          starting: 2010  # when they started
          ending: current_year
    - pmm: separator_chart
    - pmm: basic
    - pmm: imdb
    - pmm: tmdb
    - pmm: studio
    - pmm: seasonal
      template_variables:
        schedule_independence: never
        schedule_labor: never
        schedule_memorial: never
        schedule_mother: never
        schedule_thanksgiving: never
        schedule_veteran: never
    - pmm: streaming
      template_variables:
        orginals_only: true
    - pmm: universe
    - pmm: based
    overlay_files:
    - remove_overlays: false     # Set this to true to remove all overlays
    - pmm: ribbon
  TV Shows:
    report_path: config/missing/TV_missing.yml  # NOTE: this seems to do nothing at the moment
    template_variables:
      collection_mode: hide            # hide the collections in the "Library" tab
      placeholder_imdb_id: tt11834592  # put something in the placeholder so it'll be hidden - Gaslit (2022)
    collection_files:  # NOTE: this was metadata_path when I first started
    - folder: config/collections/TV
    - pmm: separator_award
    - pmm: bafta
      template_variables:
        data:
          starting: 2014  # when they started
          ending: current_year
    - pmm: golden
      template_variables:
        data:
          starting: 1944  # when they started
          ending: current_year
    - pmm: emmy
      template_variables:
        data:
          starting: 1948  # when they started
          ending: current_year
    - pmm: separator_chart
    - pmm: basic
    - pmm: imdb
    - pmm: tmdb
    - pmm: network
    - pmm: streaming
      template_variables:
        orginals_only: true
    - pmm: based
    overlay_files:
    - remove_overlays: false     # Set this to true to remove all overlays
    - pmm: ribbon
    - pmm: status
playlist_files:
- pmm: playlist                  # This is a file within PMM's defaults folder
  template_variables:
    libraries: Movies, TV Shows  # list of libraries that you want the PMM Defaults playlists to look at
settings:
  cache: true
  cache_expiration: 60  # days
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: false  # set to true if you want a ridiculous amount of output
  show_missing_assets: true
  save_report: false   # this is probably why the report_path settings do nothing
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  run_order:
  - operations
  - metadata
  - collections
  - overlays
webhooks:                        # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: <redacted>
  token: <redacted>
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                            # REQUIRED for the script to run
  apikey: <redacted>
  language: en
  cache_expiration: 60
  region:
tautulli:                        # Can be individually specified per library as well
  url: <redacted>
  apikey: ################################
github:
  token: ################################
omdb:
  apikey: ########
  cache_expiration: 60
mdblist:
  apikey: #########################
  cache_expiration: 60
notifiarr:
  apikey: ####################################
anidb:                           # Not required for AniDB builders unless you want mature content
  username: ######
  password: ######
  language: en
  client:
radarr:                          # Can be individually specified per library as well
  url: <redacted>
  token: ################################
  add_missing: false
  add_existing: false
  root_folder_path: S:/Movies
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false
sonarr:                          # Can be individually specified per library as well
  url: <redacted>
  token: ################################
  add_missing: false
  add_existing: false
  root_folder_path: S:/TV Shows
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false
trakt:
  client_id: <redacted>
  client_secret: <redacted>
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
mal:
  client_id: ####################
  client_secret: ####################
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
