libraries:
  Movies:
    operations:
      - schedule: daily
        assets_for_all: true
      - schedule: never               # this doesn't need to happen repeatedly, but I'll keep it around for sometimes
        mass_poster_update:
          source: lock                # stop changing my posters, Plex!
          seasons: false              # quiet a warning
          episodes: false             # quiet a warning
      - schedule: weekly(sunday)
        mass_audience_rating_update: mdb_tomatoesaudience
        mass_critic_rating_update: mdb_tomatoes
    report_path: config/missing/Movies_missing.yml  # NOTE: this seems to do nothing at the moment
    template_variables:
      collection_mode: hide           # hide the collections in the "Library" tab
      placeholder_imdb_id: tt0117887  # put something in the placeholder so it'll be hidden - That Thing You Do! (1996)
    metadata_files:
      - folder: config/metadata/Movies
    collection_files:
      - folder: config/collections/Movies
      - folder: config/collections/shared
    overlay_files:
      # "overlays" is where the actual overlay images are stored
      - folder: config/overlay/Movies
      - folder: config/overlay/shared
  TV Shows:
    operations:
      - schedule: daily
        assets_for_all: true
      - schedule: never               # this doesn't need to happen repeatedly, but I'll keep it around for sometimes
        mass_poster_update:
          source: lock                 # stop changing my posters, Plex!
          seasons: true
          episodes: false              # this is too much
      - schedule: weekly(sunday)
        mass_audience_rating_update: mdb_tomatoesaudience
        mass_critic_rating_update: mdb_tomatoes
    report_path: config/missing/TV_missing.yml  # NOTE: this seems to do nothing at the moment
    template_variables:
      collection_mode: hide            # hide the collections in the "Library" tab
      placeholder_imdb_id: tt11834592  # put something in the placeholder so it'll be hidden - Gaslit (2022)
    metadata_files:
      - folder: config/metadata/TV
    collection_files:
      - folder: config/collections/TV
      - folder: config/collections/shared
    overlay_files:
      # "overlays" is where the actual overlay images are stored
      - folder: config/overlay/TV
      - folder: config/overlay/shared
playlist_files:
  - folder: config/playlists
    template_variables:
      libraries: Movies, TV Shows
  - pmm: playlist
    template_variables:
      libraries: Movies, TV Shows
settings:
  cache: true
  cache_expiration: 60  # days
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 2  # images is one, and collections or movies or franchises or whatever is two
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: false
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: false  # set to true if you want a ridiculous amount of output
  show_missing_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  save_report: false   # this is probably why the report_path settings do nothing
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  run_order:
    - operations
    - metadata
    - collections
    - overlays
webhooks:                        # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: <redacted>
  token: <redacted>
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                            # REQUIRED for the script to run
  apikey: <redacted>
  language: en
  cache_expiration: 60
  region:
tautulli:                        # Can be individually specified per library as well
  url: <redacted>
  apikey: ################################
github:
  token: ################################
omdb:
  apikey: ########
  cache_expiration: 60
mdblist:
  apikey: #########################
  cache_expiration: 60
notifiarr:
  apikey: ####################################
anidb:                           # Not required for AniDB builders unless you want mature content
  username: ######
  password: ######
  language: en
  client:
radarr:                          # Can be individually specified per library as well
  url: <redacted>
  token: ################################
  add_missing: false
  add_existing: false
  upgrade_existing: false
  root_folder_path: /share/Download
  monitor: movie
  availability: announced
  quality_profile: "720->DVD w/ 1080"
  tag: PMM
  search: true
  radarr_path:  # leaving this out, only important with add_existing or radarr_add_all
  plex_path:    # leaving this out, only important with add_existing or radarr_add_all
  ignore_cache: false
sonarr:                          # Can be individually specified per library as well
  url: <redacted>
  token: ################################
  add_missing: false
  add_existing: false
  upgrade_existing: false
  root_folder_path: /share/Download
  monitor: missing
  quality_profile: "720->TV w/ 1080"
  # I don't want only English, and I don't see language profiles in my Sonarr anyway (v4)
  # language_profile: English
  series_type: standard
  season_folder: true
  tag: PMM
  search: true
  cutoff_search: false
  sonarr_path:  # leaving this out, only important with add_existing or sonarr_add_all
  plex_path:    # leaving this out, only important with add_existing or sonarr_add_all
  ignore_cache: false
trakt:
  client_id: <redacted>
  client_secret: <redacted>
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
mal:
  client_id: ####################
  client_secret: ####################
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
